# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 140ce2958d6143a57bb745295de5c1494526978f1b93531af9d3d7f3e166dae226cb88db6da698c9aa25551fd21d4a22fb0e9331bde1a27ca90557509db87387

test:
  secret_key_base: 738cd6d123faa5b1785ecba31865000222f8726f7e3332413c8aeab0218642e2d478f126186da23801428075f707980897740ad5b37057728d193cbbb9ed9dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
